### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by elimisteve** [jvasile/Plinth#12]
Here's what I ran after cloning the Plinth repo:

```
make
cd vendor/exmachina
sudo python ./exmachina.py &
cd ../../
./plinth.py
```

Output:

```
127.0.0.1 8000
```

When I visit http://127.0.0.1:8000, this is what I see:

```
400 Bad Request

Illegal cookie name __utma

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 621, in respond
    self.process_headers()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 722, in process_headers
    raise cherrypy.HTTPError(400, msg)
HTTPError: (400, 'Illegal cookie name __utma')
```

Since I'm running all this on a 64-bit Linux desktop (and not a DreamPlug), obviously I can't configure the FreedomBox I don't have. What should I do to be able to at least see what Plinth looks like?

**Comment by elimisteve** [comment]
OS: 64-bit Linux as I said above. Browser: Chrome 24.

**Comment by elimisteve** [comment]
I just used a browser without old (probably a local Django site's) cookies from http://127.0.0.1:8000. I'm not sure if this is an issue with CherryPy or what, or the degree to which this should be a concern (many other things seem more important), but... now you know the above can occur :-).
