### ISSUE TITLE
Error: 500

### ISSUE THREAD

**Issue by ghost** [jvasile/Plinth#17]
Says "This is an internal error and not something you caused or can fix."
Can't log in or anything. This a fresh install from apt on a fresh crunchbang upgraded to testing.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/share/plinth/python/plinth/modules/first_boot/first_boot.py", line 82, in index
    return self.state0(_args, *_kwargs)
  File "/usr/share/plinth/python/plinth/modules/first_boot/first_boot.py", line 131, in state0
    messages=messages)
  File "/usr/share/plinth/python/plinth/util.py", line 81, in render_template
    return render_to_string(template + '.html', kwargs)
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: firstboot_state0.html

**Comment by jvalleroy** [comment]
I think it would be better to open this issue on @NickDaly's fork:
https://github.com/nickdaly/plinth/issues
That one is more active and is used for the debian packages.

**Comment by brokenisuseless** [comment]
jvalleroy I couldn't agree more but the link in plinth its self sends you here, to report, someone might want to change that, I can confirm the broken

**Comment by NickDaly** [comment]
Confirming this bug.

I'm looking into it now, sorry for the delay.

**Comment by SunilMohanAdapa** [comment]
This is fixed by @jvalleroy with merge request #90.
